language: haskell

sudo: required

env:
  - GHCVER=7.10.1 CABALVER=1.22

before_install:
  - cd ..

  # # Install SDL.
  # - wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  # - tar xf SDL2-*.tar.gz
  # - cd SDL2-* && ./configure && make && sudo make install && cd ..

  # # Install SDL_image.
  # - wget -q http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  # - tar xf SDL2_image-*.tar.gz
  # - cd SDL2_image-* && ./configure && make && sudo make install && cd ..

  # Install GHC and cabal-install.
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy
  - export CABAL=cabal-$CABALVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - pwd
  - ls -l .
  - cat .cabal/config
  - rm -rf .cabal
  - $CABAL update

# install:
#   # Install haskell-game/sdl2.
#   - git clone https://github.com/haskell-game/sdl2.git
#   - cd sdl2 && cabal install -j && cd ..

script:
  - cd sdl2-image
  # - $CABAL configure
  # - $CABAL install --only-dependencies -j
  # - $CABAL build
